import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Glory } from "next/font/google";
import Navbar from "./Navbar";

const glory = Glory({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-glory",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={glory.variable}>
      <body className={glory.className}>
        <Theme accentColor="tomato" grayColor="olive">
          <Navbar />
          <main className="p-5">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
